### ISSUE TITLE
Better default formats for Time objects

### ISSUE THREAD

**Issue by triskweline** [makandra/katapult#9]
```
  time:
    formats:
      default: "%d.%m.%Y %H:%M"
      exact: "%d.%m.%Y %H:%M:%S"
      time: "%H:%M"
      exact_time: "%H:%M:%S"
```
